####################
#
# HTCondor submit description file
#
####################
$BATCH_NAME
executable              = job_DeepNTuples.sh
arguments               = "$(pythonFilename) $(processID) $(MiniAodFile) '$CUSTOMISE_ARG'"
initialdir              = job$(processID)
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
transfer_input_files    = ../$CONFIG_FILE ../$SETUP_SCRIPT $(MiniAodFileTransfer)
transfer_output_files   = ""
log                     = job.log
error                   = job.err
output                  = job.out
RequestCpus             = $N_CPU
request_memory          = $MEMORY

$REQUIREMENTS

queue pythonFilename, processID, MiniAodFile, MiniAodFileTransfer from arguments.txt
